-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.migrations (
  id integer NOT NULL DEFAULT nextval('migrations_id_seq'::regclass),
  migration character varying NOT NULL,
  batch integer NOT NULL,
  CONSTRAINT migrations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email character varying NOT NULL UNIQUE,
  email_verified_at timestamp without time zone,
  password character varying NOT NULL,
  role character varying NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  first_name character varying,
  last_name character varying,
  phone character varying,
  avatar_url character varying,
  locale character varying NOT NULL DEFAULT 'fr'::character varying,
  remember_token character varying,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  last_login_at timestamp without time zone,
  deleted_at timestamp without time zone,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.social_accounts (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  provider character varying NOT NULL,
  provider_id character varying NOT NULL,
  provider_token character varying,
  provider_refresh_token character varying,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT social_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT social_accounts_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.auth_tokens (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  device_name character varying,
  device_type character varying,
  ip_address character varying,
  user_agent text,
  last_used_at timestamp without time zone,
  expires_at timestamp without time zone,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT auth_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT auth_tokens_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  bio character varying,
  title character varying,
  country character varying,
  city character varying,
  address character varying,
  gender character varying,
  birth_date date,
  website_url character varying,
  linkedin_url character varying,
  github_url character varying,
  phone_secondary character varying,
  is_visible boolean NOT NULL DEFAULT true,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.client_profiles (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  company_name character varying,
  company_website character varying,
  company_size character varying,
  industry character varying,
  total_projects_posted integer NOT NULL DEFAULT 0,
  total_spent numeric NOT NULL DEFAULT '0'::numeric,
  average_rating numeric NOT NULL DEFAULT '0'::numeric,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT client_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT client_profiles_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.freelance_profiles (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  professional_title character varying,
  experience_level character varying,
  years_experience integer NOT NULL DEFAULT 0,
  education_level character varying,
  hourly_rate_min character varying,
  hourly_rate_max character varying,
  currency character varying NOT NULL DEFAULT 'XOF'::character varying,
  is_available boolean NOT NULL DEFAULT true,
  total_projects_completed integer NOT NULL DEFAULT 0,
  total_projects_in_progress integer NOT NULL DEFAULT 0,
  average_rating numeric NOT NULL DEFAULT '0'::numeric,
  total_reviews integer NOT NULL DEFAULT 0,
  total_earnings numeric NOT NULL DEFAULT '0'::numeric,
  success_rate numeric NOT NULL DEFAULT '0'::numeric,
  last_active_at timestamp without time zone,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT freelance_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT freelance_profiles_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.job_categories (
  id uuid NOT NULL,
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  description text,
  icon character varying,
  color character varying,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  parent_id uuid,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT job_categories_pkey PRIMARY KEY (id),
  CONSTRAINT job_categories_parent_id_foreign FOREIGN KEY (parent_id) REFERENCES public.job_categories(id)
);
CREATE TABLE public.skills (
  id uuid NOT NULL,
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  category_id uuid,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT skills_pkey PRIMARY KEY (id),
  CONSTRAINT skills_category_id_foreign FOREIGN KEY (category_id) REFERENCES public.job_categories(id)
);
CREATE TABLE public.freelance_skills (
  id uuid NOT NULL,
  freelance_profile_id uuid NOT NULL,
  skill_id uuid NOT NULL,
  proficiency_level character varying,
  years_experience integer,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT freelance_skills_pkey PRIMARY KEY (id),
  CONSTRAINT freelance_skills_freelance_profile_id_foreign FOREIGN KEY (freelance_profile_id) REFERENCES public.freelance_profiles(id),
  CONSTRAINT freelance_skills_skill_id_foreign FOREIGN KEY (skill_id) REFERENCES public.skills(id)
);
CREATE TABLE public.freelance_languages (
  id uuid NOT NULL,
  freelance_profile_id uuid NOT NULL,
  language character varying NOT NULL,
  proficiency_level character varying,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT freelance_languages_pkey PRIMARY KEY (id),
  CONSTRAINT freelance_languages_freelance_profile_id_foreign FOREIGN KEY (freelance_profile_id) REFERENCES public.freelance_profiles(id)
);
CREATE TABLE public.portfolio_items (
  id uuid NOT NULL,
  freelance_profile_id uuid NOT NULL,
  title character varying NOT NULL,
  description text,
  project_url character varying,
  completed_date date,
  is_featured boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT portfolio_items_pkey PRIMARY KEY (id),
  CONSTRAINT portfolio_items_freelance_profile_id_foreign FOREIGN KEY (freelance_profile_id) REFERENCES public.freelance_profiles(id)
);
CREATE TABLE public.portfolio_files (
  id uuid NOT NULL,
  portfolio_item_id uuid NOT NULL,
  file_url character varying NOT NULL,
  file_type character varying,
  file_name character varying,
  file_size integer,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT portfolio_files_pkey PRIMARY KEY (id),
  CONSTRAINT portfolio_files_portfolio_item_id_foreign FOREIGN KEY (portfolio_item_id) REFERENCES public.portfolio_items(id)
);
CREATE TABLE public.verifications (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  type character varying NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  document_url character varying,
  admin_notes text,
  reviewed_by uuid,
  reviewed_at timestamp without time zone,
  expires_at date,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT verifications_pkey PRIMARY KEY (id),
  CONSTRAINT verifications_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT verifications_reviewed_by_foreign FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.subscription_plans_config (
  id uuid NOT NULL,
  plan character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  description text,
  price_monthly numeric NOT NULL,
  price_yearly numeric NOT NULL,
  max_projects integer,
  max_quotes_per_month integer,
  has_verified_badge boolean NOT NULL DEFAULT false,
  has_boost_option boolean NOT NULL DEFAULT false,
  features json,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT subscription_plans_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.freelance_subscriptions (
  id uuid NOT NULL,
  freelance_profile_id uuid NOT NULL,
  plan_id uuid NOT NULL,
  status character varying NOT NULL DEFAULT 'trial'::character varying,
  started_at timestamp without time zone,
  ends_at timestamp without time zone,
  trial_ends_at timestamp without time zone,
  cancelled_at timestamp without time zone,
  billing_cycle character varying NOT NULL DEFAULT 'monthly'::character varying,
  amount_paid numeric NOT NULL DEFAULT '0'::numeric,
  payment_reference character varying,
  auto_renew boolean NOT NULL DEFAULT true,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT freelance_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT freelance_subscriptions_freelance_profile_id_foreign FOREIGN KEY (freelance_profile_id) REFERENCES public.freelance_profiles(id),
  CONSTRAINT freelance_subscriptions_plan_id_foreign FOREIGN KEY (plan_id) REFERENCES public.subscription_plans_config(id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL,
  client_id uuid NOT NULL,
  category_id uuid,
  title character varying NOT NULL,
  description text,
  status character varying NOT NULL DEFAULT 'draft'::character varying,
  budget_min numeric,
  budget_max numeric,
  currency character varying NOT NULL DEFAULT 'XOF'::character varying,
  experience_level character varying,
  duration_days integer,
  required_skills json,
  project_type character varying,
  is_featured boolean NOT NULL DEFAULT false,
  is_urgent boolean NOT NULL DEFAULT false,
  is_remote boolean NOT NULL DEFAULT true,
  location character varying,
  quotes_count integer NOT NULL DEFAULT 0,
  views_count integer NOT NULL DEFAULT 0,
  published_at timestamp without time zone,
  deadline_at timestamp without time zone,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  deleted_at timestamp without time zone,
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_client_id_foreign FOREIGN KEY (client_id) REFERENCES public.users(id),
  CONSTRAINT projects_category_id_foreign FOREIGN KEY (category_id) REFERENCES public.job_categories(id)
);
CREATE TABLE public.project_files (
  id uuid NOT NULL,
  project_id uuid NOT NULL,
  file_url character varying NOT NULL,
  file_name character varying,
  file_type character varying,
  file_size integer,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT project_files_pkey PRIMARY KEY (id),
  CONSTRAINT project_files_project_id_foreign FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.quotes (
  id uuid NOT NULL,
  project_id uuid NOT NULL,
  freelance_id uuid NOT NULL,
  proposal text,
  amount numeric NOT NULL,
  currency character varying NOT NULL DEFAULT 'XOF'::character varying,
  estimated_duration integer,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  read_at timestamp without time zone,
  responded_at timestamp without time zone,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  deleted_at timestamp without time zone,
  CONSTRAINT quotes_pkey PRIMARY KEY (id),
  CONSTRAINT quotes_project_id_foreign FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT quotes_freelance_id_foreign FOREIGN KEY (freelance_id) REFERENCES public.users(id)
);
CREATE TABLE public.contracts (
  id uuid NOT NULL,
  project_id uuid NOT NULL,
  quote_id uuid,
  client_id uuid NOT NULL,
  freelance_id uuid NOT NULL,
  title character varying NOT NULL,
  description text,
  status character varying NOT NULL DEFAULT 'draft'::character varying,
  total_amount numeric NOT NULL,
  currency character varying NOT NULL DEFAULT 'XOF'::character varying,
  platform_fee numeric NOT NULL DEFAULT '0'::numeric,
  freelance_amount numeric NOT NULL DEFAULT '0'::numeric,
  start_date date,
  end_date date,
  terms_conditions text,
  client_signed_at timestamp without time zone,
  freelance_signed_at timestamp without time zone,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  deleted_at timestamp without time zone,
  CONSTRAINT contracts_pkey PRIMARY KEY (id),
  CONSTRAINT contracts_project_id_foreign FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT contracts_quote_id_foreign FOREIGN KEY (quote_id) REFERENCES public.quotes(id),
  CONSTRAINT contracts_client_id_foreign FOREIGN KEY (client_id) REFERENCES public.users(id),
  CONSTRAINT contracts_freelance_id_foreign FOREIGN KEY (freelance_id) REFERENCES public.users(id)
);
CREATE TABLE public.milestones (
  id uuid NOT NULL,
  contract_id uuid NOT NULL,
  title character varying NOT NULL,
  description text,
  amount numeric NOT NULL DEFAULT '0'::numeric,
  due_date date,
  is_completed boolean NOT NULL DEFAULT false,
  completed_at timestamp without time zone,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  status character varying,
  delivered_at timestamp without time zone,
  validated_at timestamp without time zone,
  CONSTRAINT milestones_pkey PRIMARY KEY (id),
  CONSTRAINT milestones_contract_id_foreign FOREIGN KEY (contract_id) REFERENCES public.contracts(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL,
  contract_id uuid,
  user_id uuid NOT NULL,
  amount numeric NOT NULL,
  platform_fee numeric NOT NULL DEFAULT '0'::numeric,
  net_amount numeric NOT NULL DEFAULT '0'::numeric,
  currency character varying NOT NULL DEFAULT 'XOF'::character varying,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  channel character varying,
  operator character varying,
  transaction_type character varying NOT NULL,
  reference character varying UNIQUE,
  description character varying,
  metadata json,
  paid_at timestamp without time zone,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  transaction_id uuid,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_contract_id_foreign FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT payments_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT payments_transaction_id_foreign FOREIGN KEY (transaction_id) REFERENCES public.transactions(id)
);
CREATE TABLE public.genius_pay_webhooks (
  id uuid NOT NULL,
  event_type character varying NOT NULL,
  payload json NOT NULL,
  signature character varying,
  is_processed boolean NOT NULL DEFAULT false,
  processed_at timestamp without time zone,
  error_message text,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT genius_pay_webhooks_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payment_sync_log (
  id uuid NOT NULL,
  payment_id uuid NOT NULL,
  action character varying NOT NULL,
  status character varying NOT NULL,
  request_data text,
  response_data text,
  error_message text,
  ip_address character varying,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT payment_sync_log_pkey PRIMARY KEY (id),
  CONSTRAINT payment_sync_log_payment_id_foreign FOREIGN KEY (payment_id) REFERENCES public.payments(id)
);
CREATE TABLE public.escrows (
  id uuid NOT NULL,
  payment_id uuid,
  contract_id uuid,
  status character varying NOT NULL DEFAULT 'holding'::character varying,
  amount numeric NOT NULL,
  held_amount numeric NOT NULL DEFAULT '0'::numeric,
  released_amount numeric NOT NULL DEFAULT '0'::numeric,
  refunded_amount numeric NOT NULL DEFAULT '0'::numeric,
  held_at timestamp without time zone,
  released_at timestamp without time zone,
  refunded_at timestamp without time zone,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT escrows_pkey PRIMARY KEY (id),
  CONSTRAINT escrows_contract_id_foreign FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT escrows_payment_id_foreign FOREIGN KEY (payment_id) REFERENCES public.payments(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL,
  contract_id uuid NOT NULL,
  payment_id uuid,
  invoice_number character varying NOT NULL UNIQUE,
  amount numeric NOT NULL,
  platform_fee numeric NOT NULL DEFAULT '0'::numeric,
  net_amount numeric NOT NULL DEFAULT '0'::numeric,
  currency character varying NOT NULL DEFAULT 'XOF'::character varying,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  issue_date date NOT NULL,
  due_date date,
  paid_date date,
  invoice_data json,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_contract_id_foreign FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT invoices_payment_id_foreign FOREIGN KEY (payment_id) REFERENCES public.payments(id)
);
CREATE TABLE public.wallets (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  balance numeric NOT NULL DEFAULT '0'::numeric,
  pending_balance numeric NOT NULL DEFAULT '0'::numeric,
  total_earned numeric NOT NULL DEFAULT '0'::numeric,
  total_withdrawn numeric NOT NULL DEFAULT '0'::numeric,
  currency character varying NOT NULL DEFAULT 'XOF'::character varying,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT wallets_pkey PRIMARY KEY (id),
  CONSTRAINT wallets_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.wallet_transactions (
  id uuid NOT NULL,
  wallet_id uuid NOT NULL,
  type character varying NOT NULL,
  amount numeric NOT NULL,
  balance_before numeric NOT NULL,
  balance_after numeric NOT NULL,
  description character varying,
  reference character varying,
  metadata json,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT wallet_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT wallet_transactions_wallet_id_foreign FOREIGN KEY (wallet_id) REFERENCES public.wallets(id)
);
CREATE TABLE public.withdrawal_requests (
  id uuid NOT NULL,
  wallet_id uuid NOT NULL,
  user_id uuid NOT NULL,
  amount numeric NOT NULL,
  fee numeric NOT NULL DEFAULT '0'::numeric,
  net_amount numeric NOT NULL DEFAULT '0'::numeric,
  method character varying NOT NULL,
  account_identifier character varying,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  admin_notes text,
  processed_by uuid,
  processed_at timestamp without time zone,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT withdrawal_requests_pkey PRIMARY KEY (id),
  CONSTRAINT withdrawal_requests_wallet_id_foreign FOREIGN KEY (wallet_id) REFERENCES public.wallets(id),
  CONSTRAINT withdrawal_requests_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT withdrawal_requests_processed_by_foreign FOREIGN KEY (processed_by) REFERENCES public.users(id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL,
  project_id uuid,
  contract_id uuid,
  subject character varying,
  last_message_at timestamp without time zone,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_project_id_foreign FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT conversations_contract_id_foreign FOREIGN KEY (contract_id) REFERENCES public.contracts(id)
);
CREATE TABLE public.conversation_participants (
  id uuid NOT NULL,
  conversation_id uuid NOT NULL,
  user_id uuid NOT NULL,
  last_read_at timestamp without time zone,
  is_muted boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT conversation_participants_pkey PRIMARY KEY (id),
  CONSTRAINT conversation_participants_conversation_id_foreign FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT conversation_participants_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL,
  conversation_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  content text NOT NULL,
  status character varying NOT NULL DEFAULT 'sent'::character varying,
  read_at timestamp without time zone,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  deleted_at timestamp without time zone,
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_conversation_id_foreign FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT messages_sender_id_foreign FOREIGN KEY (sender_id) REFERENCES public.users(id)
);
CREATE TABLE public.message_files (
  id uuid NOT NULL,
  message_id uuid NOT NULL,
  file_url character varying NOT NULL,
  file_name character varying,
  file_type character varying,
  file_size integer,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT message_files_pkey PRIMARY KEY (id),
  CONSTRAINT message_files_message_id_foreign FOREIGN KEY (message_id) REFERENCES public.messages(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  type character varying NOT NULL,
  title character varying NOT NULL,
  body text,
  data json,
  action_url character varying,
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamp without time zone,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL,
  contract_id uuid NOT NULL,
  reviewer_id uuid NOT NULL,
  reviewee_id uuid NOT NULL,
  rating integer NOT NULL,
  comment text,
  criteria_ratings json,
  is_flagged boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  deleted_at timestamp without time zone,
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_contract_id_foreign FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT reviews_reviewer_id_foreign FOREIGN KEY (reviewer_id) REFERENCES public.users(id),
  CONSTRAINT reviews_reviewee_id_foreign FOREIGN KEY (reviewee_id) REFERENCES public.users(id)
);
CREATE TABLE public.review_replies (
  id uuid NOT NULL,
  review_id uuid NOT NULL,
  user_id uuid NOT NULL,
  comment text NOT NULL,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT review_replies_pkey PRIMARY KEY (id),
  CONSTRAINT review_replies_review_id_foreign FOREIGN KEY (review_id) REFERENCES public.reviews(id),
  CONSTRAINT review_replies_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.reports (
  id uuid NOT NULL,
  reporter_id uuid NOT NULL,
  reported_user_id uuid NOT NULL,
  type character varying NOT NULL,
  status character varying NOT NULL DEFAULT 'open'::character varying,
  description text NOT NULL,
  evidence json,
  admin_notes text,
  reviewed_by uuid,
  reviewed_at timestamp without time zone,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT reports_pkey PRIMARY KEY (id),
  CONSTRAINT reports_reporter_id_foreign FOREIGN KEY (reporter_id) REFERENCES public.users(id),
  CONSTRAINT reports_reported_user_id_foreign FOREIGN KEY (reported_user_id) REFERENCES public.users(id),
  CONSTRAINT reports_reviewed_by_foreign FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.disputes (
  id uuid NOT NULL,
  contract_id uuid NOT NULL,
  raised_by uuid NOT NULL,
  status character varying NOT NULL DEFAULT 'open'::character varying,
  reason text NOT NULL,
  evidence json,
  admin_notes text,
  resolved_by uuid,
  resolved_at timestamp without time zone,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT disputes_pkey PRIMARY KEY (id),
  CONSTRAINT disputes_contract_id_foreign FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT disputes_raised_by_foreign FOREIGN KEY (raised_by) REFERENCES public.users(id),
  CONSTRAINT disputes_resolved_by_foreign FOREIGN KEY (resolved_by) REFERENCES public.users(id)
);
CREATE TABLE public.boosts (
  id uuid NOT NULL,
  freelance_profile_id uuid NOT NULL,
  target_type character varying NOT NULL,
  target_id uuid,
  duration character varying NOT NULL,
  amount_paid numeric NOT NULL,
  payment_reference character varying,
  started_at timestamp without time zone NOT NULL,
  ends_at timestamp without time zone NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT boosts_pkey PRIMARY KEY (id),
  CONSTRAINT boosts_freelance_profile_id_foreign FOREIGN KEY (freelance_profile_id) REFERENCES public.freelance_profiles(id)
);
CREATE TABLE public.verified_badges (
  id uuid NOT NULL,
  freelance_profile_id uuid NOT NULL,
  verification_id uuid,
  badge_type character varying NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  granted_at timestamp without time zone NOT NULL,
  expires_at timestamp without time zone,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT verified_badges_pkey PRIMARY KEY (id),
  CONSTRAINT verified_badges_freelance_profile_id_foreign FOREIGN KEY (freelance_profile_id) REFERENCES public.freelance_profiles(id),
  CONSTRAINT verified_badges_verification_id_foreign FOREIGN KEY (verification_id) REFERENCES public.verifications(id)
);
CREATE TABLE public.admin_logs (
  id uuid NOT NULL,
  admin_id uuid NOT NULL,
  action character varying NOT NULL,
  entity_type character varying,
  entity_id character varying,
  old_values json,
  new_values json,
  ip_address character varying,
  user_agent text,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT admin_logs_pkey PRIMARY KEY (id),
  CONSTRAINT admin_logs_admin_id_foreign FOREIGN KEY (admin_id) REFERENCES public.users(id)
);
CREATE TABLE public.platform_settings (
  id uuid NOT NULL,
  key character varying NOT NULL UNIQUE,
  value text,
  group character varying NOT NULL DEFAULT 'general'::character varying,
  type character varying NOT NULL DEFAULT 'string'::character varying,
  description text,
  is_public boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT platform_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  type character varying NOT NULL,
  amount numeric NOT NULL,
  currency character varying NOT NULL DEFAULT 'XOF'::character varying,
  description text,
  payment_channel character varying,
  payment_operator character varying,
  operator_status character varying,
  operator_transaction_id character varying,
  operator_reference character varying,
  payment_url character varying,
  metadata json,
  paid_at timestamp without time zone,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.referral_codes (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  code character varying NOT NULL UNIQUE,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT referral_codes_pkey PRIMARY KEY (id),
  CONSTRAINT referral_codes_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.referrals (
  id uuid NOT NULL,
  referrer_id uuid NOT NULL,
  referred_id uuid NOT NULL UNIQUE,
  referral_code_id uuid NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  reward_amount numeric NOT NULL DEFAULT '0'::numeric,
  paid_at timestamp without time zone,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  CONSTRAINT referrals_pkey PRIMARY KEY (id),
  CONSTRAINT referrals_referrer_id_foreign FOREIGN KEY (referrer_id) REFERENCES public.users(id),
  CONSTRAINT referrals_referred_id_foreign FOREIGN KEY (referred_id) REFERENCES public.users(id),
  CONSTRAINT referrals_referral_code_id_foreign FOREIGN KEY (referral_code_id) REFERENCES public.referral_codes(id)
);
